### ISSUE TITLE
What container are you displaying ncmpcpp in for artwork output?

### ISSUE THREAD

**Issue by bearcatsandor** [addy-dclxvi/almighty-dotfiles#14]
In your ~/.ncmpcpp/art-dark.sh file you display the album art in the ncmpcpp window.  What are you displaying it in? I've tried a few terminal programs (alacrity, kitty) and none of them display artwork using that  printf statement.

Thanks

**Comment by addy-dclxvi** [comment]
It's just rxvt-unicode with pixmap enabled (Debian & derivative have it
enabled by default, Arch & derivative need to enable it manually on build
or simply install rxvt-unicode-pixmap from AUR)

**Comment by bearcatsandor** [comment]
Thank you. Using the useflag gdk-pixbuff did the trick! I wish i could get it working in kitty, but that's another project.
