### ISSUE TITLE
yo boi , godd rice but how did u get gtk minimize, maximize, close icons in the openbox rice?

### ISSUE THREAD

**Issue by daUnknownCoder** [addy-dclxvi/almighty-dotfiles#23]

**Comment by dcindallas** [comment]
> _No description provided._

lxappearance and gtk installed that's about it mate and who you calling boi?

**Comment by daUnknownCoder** [comment]
> > _No description provided._
> 
> lxappearance and gtk installed that's about it mate and who you calling boi?

imma talking abt this https://raw.githubusercontent.com/addy-dclxvi/almighty-dotfiles/master/preview-openbox.jpg, the upper corner, in my system i dont get these close and all icons
