### ISSUE TITLE
Question about left dock

### ISSUE THREAD

**Issue by dreamcat4** [addy-dclxvi/almighty-dotfiles#9]
Hi there,
Just noticed your work on Reddit. However the thread was archived, so cannot ask over on it anymore.

My question is:

What is this left dock bar in your desktops show in the links below? The software that displays that. Because I would like to try that. Thank you.

https://raw.githubusercontent.com/addy-dclxvi/almighty-dotfiles/master/preview-vim.jpg

https://www.reddit.com/r/unixart/comments/850jjn/xfwm_and_justice_for_all/

**Comment by addy-dclxvi** [comment]
Hello Dreamcat4,

It just some buttons to launch apps & bookmarks I made using tint2. It's
available in my tint2-theme-collections repo.

**Comment by dreamcat4** [comment]
Thank you for providing these excellent customizations of tint2. Very grateful for this. Will have to try them out sometime. Have a nice day!
